### ISSUE TITLE
Coding standards fails

### ISSUE THREAD

**Issue by aleswita** [nette/coding-standard#19]
Yeastarday I see, that coding standard fails on multiple sniffs on all files in travis ci, [look.](https://travis-ci.org/aleswita/DropzoneUploader/jobs/283644985)

When i check the code in local, all sniffs passed (local on OS Windows).

I'm using version 0.7.0, but version 0.6.1 have same problem and I can not find library, where is the problem.

**Comment by TomasVotruba** [comment]
Thanks for the report

I think that might be related to changed diff package for php-cs-fixer 2.7: https://github.com/FriendsO
fPHP/PHP-CS-Fixer/pull/3074

Could you please try version 2.6 to confirm this?

```json
{
    "require": {
        "friendsofphp/php-cs-fixer": "2.7 as 2.6"
    }
}
```

**Comment by TomasVotruba** [comment]
@aleswita Any updates?

**Comment by TomasVotruba** [comment]
Could you try current `master`? I've updated dependencies on EasyCodingStandard and released new version.

**Comment by aleswita** [comment]
Same, look: https://travis-ci.org/aleswita/WebLoader/jobs/285155717

**Comment by TomasVotruba** [comment]
Thanks for trying it out
Are you able to send PR with failing test here? Minimal code where it fails, e.g. with 10 lines

**Comment by aleswita** [comment]
Done.

If I insert PR TestClass.php to my project, coding standards fails on two errors:
![vystrizek](https://user-images.githubusercontent.com/6991688/31325202-ba956d6a-acba-11e7-8e69-47143726fe07.PNG)

.. but [travis](https://travis-ci.org/nette/coding-standard/jobs/285352726) fails on 50 errors.. so I thing this caused some issue between OS Windows and Linux... probably new lines?

**Comment by TomasVotruba** [comment]
Oh, now I recall there was line endings issue: https://github.com/Symplify/Symplify/issues/254#issuecomment-317460161

After many trial and errors we solved it like this:
https://github.com/Symplify/Symplify/pull/277

So only `PHP_EOL` is supported as line ending.

**Comment by aleswita** [comment]
In Notepad++ CR LF
![vystrizek](https://user-images.githubusercontent.com/6991688/31335040-1c1d63d6-acf1-11e7-9984-517f43e74fb9.PNG)

**Comment by TomasVotruba** [comment]
Would you have any major troubles switching to `PHP_EOL`?
It's the only way to make this work I guess.

**Comment by TomasVotruba** [comment]
Would you have any major troubles switching to `PHP_EOL`?
It's the only way to make this work I guess.

**Comment by JanTvrdik** [comment]
@TomasVotruba Using PHP_EOL on Windows is generally a bad idea, because it means that source code on your machine is different from source code in repository and on server.

**Comment by TomasVotruba** [comment]
@JanTvrdik I have no experience with this. Could you provide better solution to @aleswita ?

**Comment by dg** [comment]
You should use LF on Linux & Git and CRLF on Windows.  Ie. PHP_EOL on developer machine and LF in repo. It is possible with https://git-scm.com/book/tr/v2/Customizing-Git-Git-Configuration#__code_core_autocrlf_code

**Comment by JanTvrdik** [comment]
@dg I strongly disagree. Using OS native EOL causes a lot more issues that benefits. It's quite common to access the same files from Windows / VM with any OS / Docker with any OS / Ubuntu Bash… And LF is the most portable line ending. This is also the reason why `fopen` uses binary mode by default since PHP 4.3.2. The magic conversion may break actual binary files. Even the change of hash may break some stuff.

**Comment by dg** [comment]
I have never encountered a problem yet. But I do not use the Docker.

**Comment by TomasVotruba** [comment]
@aleswita Stepping back from this repository, is this supported by https://github.com/squizlabs/PHP_CodeSniffer? If not, please move this issue there.

**Comment by dg** [comment]
It is not related to the EOL, but I see that ECS fails now due to

```
[Symplify\EasyCodingStandard\FixerRunner\Exception\Application\FixerFailedException]  
  Fixing of "src/Application/Application.php" file by "Symplify\CodingStandar           
  d\Fixer\ClassNotation\LastPropertyAndFirstMethodSeparationFixer" failed: Me           
  thod correctLineBreaks does not exist in file /home/travis/build/nette/appl           
  ication/temp/coding-standard/vendor/symplify/coding-standard/src/Fixer/Clas           
  sNotation/LastPropertyAndFirstMethodSeparationFixer.php on line 182
```

https://travis-ci.org/nette/application/jobs/299061439

**Comment by foxycode** [comment]
Probably fixed with https://github.com/nette/coding-standard/pull/32
