### ISSUE TITLE
Problem in master branch [ERROR] Call to a member function replaceTabsInToken() on null

### ISSUE THREAD

**Issue by venca-x** [nette/coding-standard#21]
I have problems wit coding standard. In the past, he worked great but now he's making mistakes.
Some packages may have been updated? There will not be any tests on the master branch.
My fork with test log problem is here: https://travis-ci.org/venca-x/coding-standard/jobs/322316979

**Comment by TomasVotruba** [comment]
I'll look on it while upgrading to @Symplify 3.0 where this is resolved.

Thanks for the report!

**Comment by TomasVotruba** [comment]
It might have been caused by some older version of PHP_CodeSniffer with combination with ECS.

I've updated to ECS 3.1: #22

And test it here: #23

Could you check if current master works for you?

**Comment by venca-x** [comment]
Thank you Thomas!
Master branch working for me. You can release the production version

**Comment by TomasVotruba** [comment]
Glad it works! :+1: 

There is one important thing to resolve #24 
Could you check and comment there?
