### ISSUE TITLE
Problem in last production version - failed: Method correctLineBreaks does not exist

### ISSUE THREAD

**Issue by venca-x** [nette/coding-standard#27]
Hello, i have problem with last stable version (composer create-project nette/coding-standard)

The problem is:
```
[Symplify\EasyCodingStandard\FixerRunner\Exception\Application\FixerFailedException]  
Fixing of "src/Stargazer.php" file by "Symplify\CodingStandard\Fixer\ClassNotation\LastPropertyAndFirstMethodSeparationFixer" 
failed: Method correctLineBreaks does not exist in file 
/home/travis/build/venca-x/nette-stargazer/temp/coding-standard/vendor/symplify/coding-standard/src/Fixer/ClassNotation/LastPropertyAndFirstMethodSeparationFixer.php on line 182   
```
The example is visible at: https://travis-ci.org/venca-x/nette-stargazer/jobs/336262719

Thanks

**Comment by dg** [comment]
It also breaks all Nette packages https://travis-ci.org/nette/application/builds/337443957

**Comment by TomasVotruba** [comment]
Related #24 #26

**Comment by dg** [comment]
How to fix it? Is the way ie. use older version of the dependencies in the composer.json so that the bug will not appear on the Travis?

**Comment by TomasVotruba** [comment]
It should be fixed by https://github.com/nette/coding-standard/pull/25/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R7

**Comment by dg** [comment]
Oh great, so should I release 0.8?

**Comment by TomasVotruba** [comment]
The build still fails on https://travis-ci.org/nette/coding-standard/jobs/331289874#L687
A file needs to be changed or removed. If you manage to resolve that, it can be merged and 0.8 released.

Personally I'd remove `ecs` file here, which just duplicated the original and recommend `vendor/bin/ecs` like any other tool.

**Comment by dg** [comment]
I understand, the pull #25 is not yet merged.

But it seems that current master works fine. So what about release current master as 0.8?

**Comment by TomasVotruba** [comment]
I think it's failing: https://travis-ci.org/nette/coding-standard/branches

**Comment by TomasVotruba** [comment]
With no error?

Might be related to this: https://github.com/nette/coding-standard/issues/27#issuecomment-363149056

**Comment by dg** [comment]
With deprecation exception.

**Comment by dg** [comment]
I hotfixed it by using ECS 3.1 and it seems that it works. 

This error https://travis-ci.org/nette/coding-standard/jobs/337664669 it probably something related to caching on Travis.
