### ISSUE TITLE
Never ending fix

### ISSUE THREAD

**Issue by trejjam** [nette/coding-standard#28]
Class with constant and method (without properties) is in never ending fix cycle by appending and removing newline before first method.

Failing example `failing/Baz.php`:
```php
<?php
declare(strict_types=1);
class Baz
{
	public const FOO = 1;

	public function bar()
	{
	}
}
```

`php coding-standard/ecs check failing --config coding-standard/coding-standard-php71.neon`

It is created by rules:
- `Nette\CodingStandard\Sniffs\WhiteSpace\FunctionSpacingSniff.Before`
- `PhpCsFixer\Fixer\ClassNotation\ClassAttributesSeparationFixer`

**Comment by dg** [comment]
It is related to the symplify/easy-coding-standard v3.1.2, used in nette/coding-standard v0.8.

It may be fixed in newer releases, which can not be used for other reasons https://github.com/nette/coding-standard/issues/27#issuecomment-363149056

**Comment by foxycode** [comment]
Probably fixed in https://github.com/nette/coding-standard/pull/32
