### ISSUE TITLE
Impossible to update to the latest version

### ISSUE THREAD

**Issue by aleswita** [nette/coding-standard#29]
Any idea how to solved?
![vystrizek](https://user-images.githubusercontent.com/6991688/36135384-183df958-108b-11e8-9a11-80d771e5f0e1.PNG)
![vystrizek](https://user-images.githubusercontent.com/6991688/36135548-1c8ed418-108c-11e8-9dce-adb33d05f2cf.PNG)
![vystrizek](https://user-images.githubusercontent.com/6991688/36135514-e379b814-108b-11e8-8b39-ed95b937dca2.PNG)

Project composer.json
```json
	"require": {
		"php": "^7.1",
		"nette/application": "^2.4",
		"nette/bootstrap": "^2.4",
		"nette/di": "^2.4",
		"nette/caching": "^2.5",
		"nette/forms": "^2.4",
		"nette/robot-loader": "~3.0.0",
		"nette/security": "^2.4",
		"nette/utils": "^2.4",

		"latte/latte": "^2.4",
		"tracy/tracy": "^2.4",

		"kdyby/translation": "~2.5.0",

		"twbs/bootstrap": "~4.0.0",
		"fortawesome/font-awesome": "~4.7.0",

		"aleswita/webloader": "~1.0",
		"aleswita/formrenderer": "~1.0"
	},
	"require-dev": {
		"nette/tester": "^2.0",
		"phpstan/phpstan": "^0.9.2",
		"phpstan/phpstan-nette": "^0.9.0",
		"nette/coding-standard": "~0.7.0"
	},
```

**Comment by dg** [comment]
This is standalone tools, it must be installed via `composer create-project` instead of `composer require`.

**Comment by aleswita** [comment]
ou, tnx :-)
