### ISSUE TITLE
Fix change class name based on file name

### ISSUE THREAD

**Issue by sallyx** [nette/coding-standard#31]
This valid piece code in file MyCalss.php

```PHP
<?php
declare(strict_types=1);

namespace App;

class MyClass {
	public const HELLO_WORLD = 'hello world';
}

echo MyClass::HELLO_WORLD, PHP_EOL;
```
Is changed by --fix to this invalid code:

```PHP
<?php
declare(strict_types=1);

namespace App;

class MyCalss {
	public const HELLO_WORLD = 'hello world';
}

echo MyClass::HELLO_WORLD, PHP_EOL;
```
I think its more resonable to fix the file name (and dont break the code), or not to fix this error automatically.  Because, how do you decide if the error is in the file name or in the class name?

**Comment by dg** [comment]
This repository is only a bunch of presets for symplify/easy-coding-standard, friendsofphp/php-cs-fixer, slevomat/coding-standard. You must report the issues to the appropriate package.
