### ISSUE TITLE
symplify/easy-coding-standard higher than 7.2.2 is incompatible

### ISSUE THREAD

**Issue by pupitooo** [nette/coding-standard#39]
`package.json` needs version of `symplify/easy-coding-standard`  to `<=7.2.2`

**Comment by dg** [comment]
Did you see this d9ebae0eca0bcf620d255573d0486126a738943e?

**Comment by pupitooo** [comment]
I found, that problem is not in new versions. Problem was in fixed version of `symplify/easy-coding-standard` on version 7.2.0. `symplify/package-builder` was instaled with version 7.2.8 and those versions are not compatible.
So sorry, this is not directly problem in this repo, but it takes me some time to find that same versions of those repositories are fine.

Thanks David!
