### ISSUE TITLE
Add package to packagist

### ISSUE THREAD

**Issue by TomasVotruba** [nette/coding-standard#4]
Hey @dg , could I ask you to add this package on packagist? I'd like to try it out on first repo, how it works and is used in practise.

https://packagist.org/packages/submit

https://github.com/nette/coding-standard

You can give me access, if you like.

**Comment by dg** [comment]
Done https://packagist.org/packages/nette/coding-standard

I dont know how to give access to you.

**Comment by TomasVotruba** [comment]
Thank you!

There is big light grey plus sign next to your photo on package page. Try adding "Tomáš Votruba" or "tomas.vot@gmail.com" there.

**Comment by TomasVotruba** [comment]
All works, thank you for setting this up!
